# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 621, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.coefficients_tab = QtWidgets.QWidget()
        self.coefficients_tab.setObjectName("coefficients_tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.coefficients_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 591, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.reaction_area = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.reaction_area.setContentsMargins(0, 0, 0, 0)
        self.reaction_area.setObjectName("reaction_area")
        self.primary_input_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.primary_input_edit.setObjectName("primary_input_edit")
        self.reaction_area.addWidget(self.primary_input_edit)
        self.input_plus_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.input_plus_lbl.setObjectName("input_plus_lbl")
        self.reaction_area.addWidget(self.input_plus_lbl)
        self.secondary_input_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.secondary_input_edit.setObjectName("secondary_input_edit")
        self.reaction_area.addWidget(self.secondary_input_edit)
        self.into_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.into_lbl.setObjectName("into_lbl")
        self.reaction_area.addWidget(self.into_lbl)
        self.primary_output_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.primary_output_edit.setObjectName("primary_output_edit")
        self.reaction_area.addWidget(self.primary_output_edit)
        self.output_plus_lbl = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.output_plus_lbl.setObjectName("output_plus_lbl")
        self.reaction_area.addWidget(self.output_plus_lbl)
        self.secondary_output_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.secondary_output_edit.setObjectName("secondary_output_edit")
        self.reaction_area.addWidget(self.secondary_output_edit)
        self.fill_reaction_btn = QtWidgets.QPushButton(self.coefficients_tab)
        self.fill_reaction_btn.setGeometry(QtCore.QRect(140, 140, 331, 23))
        self.fill_reaction_btn.setObjectName("fill_reaction_btn")
        self.fill_coefficients_btn = QtWidgets.QPushButton(self.coefficients_tab)
        self.fill_coefficients_btn.setGeometry(QtCore.QRect(140, 200, 331, 23))
        self.fill_coefficients_btn.setObjectName("fill_coefficients_btn")
        self.output_reaction_lbl = QtWidgets.QLabel(self.coefficients_tab)
        self.output_reaction_lbl.setGeometry(QtCore.QRect(10, 260, 591, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_reaction_lbl.setFont(font)
        self.output_reaction_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.output_reaction_lbl.setObjectName("output_reaction_lbl")
        self.error_lbl = QtWidgets.QLabel(self.coefficients_tab)
        self.error_lbl.setGeometry(QtCore.QRect(10, 370, 591, 21))
        self.error_lbl.setStyleSheet("color: red")
        self.error_lbl.setText("")
        self.error_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.error_lbl.setObjectName("error_lbl")
        self.tabWidget.addTab(self.coefficients_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chemistry Cheat Sheet"))
        self.input_plus_lbl.setText(_translate("MainWindow", "+"))
        self.into_lbl.setText(_translate("MainWindow", "->"))
        self.output_plus_lbl.setText(_translate("MainWindow", "+"))
        self.fill_reaction_btn.setText(_translate("MainWindow", "Попробовать заполнить продукты реакции"))
        self.fill_coefficients_btn.setText(_translate("MainWindow", "Расставить коэффициенты"))
        self.output_reaction_lbl.setText(_translate("MainWindow", "Здесь будет написана итоговая реакция с коэффициентами"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.coefficients_tab), _translate("MainWindow", "Коэффициенты УХР"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Расчет массовой доли вещества"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Расчет формулы по массовой доле"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Расчет по УХР"))
